#!/bin/bash

node_root=/opt/node

NODE_VERSION=v0.10.3

[ "$SERVICE_NODE_VERSION" ] &&
[ "$SERVICE_NODE_VERSION" != "$(node --version)" ] &&
(
    rm -rf $node_root/*
    cd $node_root
    # use binary packages
    curl -L http://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-linux-x64.tar.gz | tar -zxf-
    mv node-$NODE_VERSION-linux-x64/* $node_root
)

cd ${SERVICE_APPROOT:=.}


# Copy code to $HOME.
rsync -aH ./ $HOME/

# Install the specified dependencies.
# This will re-use already installed dependencies.
# To force the use of the latest version of a package:
# - specify a version specification in package.json;
# - or push with the "--clean" flag to discard the incremental build.
cd $HOME
[ -f package.json ] && npm install
